server:
  port: 8080

spring:
  application:
    name: ms-entrenadores

  datasource:

    url: ${DB_URL:jdbc:postgresql://localhost:5432/gym_entrenadores}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      data-source-properties:
        ssl: true
        sslmode: require
        sslfactory: org.postgresql.ssl.NonValidatingFactory

  jpa:

    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html