server:
  port: 8080

spring:
  application:
    name: ms-entrenadores

  datasource:

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        ssl: true
        sslmode: require
        sslfactory: org.postgresql.ssl.NonValidatingFactory

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html