server:
  port: 8080

spring:
  application:
    name: ms-entrenadores
  datasource:
    url: jdbc:h2:mem:entrenadoresdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

eureka:
  client:
    enabled: false

jwt:
  secret: ${JWT_SECRET:VGhpcyBpcyBhIHRlbXBvcmFyeSBzZWNyZXQga2V5IGZvciB0ZXN0aW5nIHB1cnBvc2Vz}

ms:
  clases:
    url: ${MS_CLASES_URL:http://localhost:8080}